// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type {StoryblokMultilink, StoryblokRichtext} from './storyblok';

export interface Page {
  body?: Page[];
  component: 'page';
  _uid: string;
  [k: string]: unknown;
}
